<?php

use Mageplaza\BannerSlider\Model\Config\Source\Type;

$banners = $block->getBannerCollection();
$bannerCount = is_array($banners) ? count($banners) : $banners->getSize();

if ($bannerCount === 0) {
    return;
}

$imageHelper = $this->helper('SweatyApe\BreezeMageplazaBannerSlider\Helper\BannerImage');

?>

<div data-content-type="slider" data-mage-init='{"Magento_PageBuilder/js/content-type/slider/appearance/default/widget":{"arrows":true,"dots":true,"infinite":true}}'>
    <div class="slick-list">
        <?php foreach ($banners as $banner): ?>
            <?php
            $type = $banner->getType();
            $title = $banner->getTitle();
            $url = $banner->getUrlBanner();
            $imageUrl = $banner->getImageUrl();
            $newTab = $banner->getNewtab() === '1';

            if (($type === Type::CONTENT && empty($banner->getContent())) ||
                ($type === Type::IMAGE && empty($banner->getImage()))) {
                continue;
            }

            if ($type !== Type::IMAGE) {
                continue;
            }

            $image = $imageHelper->getBannerImage($banner);
            ?>
            <div>
                <a href="<?= $block->escapeUrl($url) ?>" <?= $newTab ? 'target="_blank"' : '' ?>>
                    <img src="<?= $block->escapeUrl($imageUrl) ?>" width="<?= $image->getOriginalWidth() ?>" height="<?= $image->getOriginalHeight() ?>" alt="<?= $block->escapeHtml($title) ?>" loading="lazy" />
                </a>
            </div>
        <?php endforeach; ?>
    </div>
</div>